# Generated by Django 3.1.7 on 2022-06-26 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Судья Ф.И.О. ')),
                ('adress_mail', models.EmailField(blank=True, default=None, max_length=300, null=True, verbose_name='Электронный адрес ')),
                ('contact_phone', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Контактный телефон ')),
                ('message', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Судья Ф.И.О ',
                'verbose_name_plural': 'Судьи Ф.И.О',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='judge_help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Помошник судьи  ФИО')),
                ('message', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Помошник судьи ',
                'verbose_name_plural': 'Помошники судей',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ListEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Событие утверждения')),
                ('message', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Список окончания сроков вступления в силу ',
                'verbose_name_plural': 'Списки окончания сроков вступления в силу',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Имя операции ')),
                ('message', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Событие ',
                'verbose_name_plural': 'События',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Наименование')),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статус  судебной оперции',
                'verbose_name_plural': 'Статусы судебных операций',
            },
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Имя ')),
                ('surname', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Фамилия ')),
                ('midlename', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Отчество ')),
                ('phone', models.CharField(blank=True, default=None, max_length=13, null=True, verbose_name='Номер телефона')),
                ('post_mail', models.EmailField(blank=True, default=None, max_length=100, null=True, verbose_name='Адрес Эл.почты')),
                ('work_mail', models.EmailField(blank=True, default=None, max_length=100, null=True, verbose_name='Адрес Эл.почты рабочей')),
                ('link_social', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Адрес в соц.сети')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сотрудник ',
                'verbose_name_plural': 'Сотрудники ',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ListCourt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Наименование суда ')),
                ('adress', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Адрес Суда ')),
                ('adress_post', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Почтовый адрес ')),
                ('adress_mail', models.EmailField(blank=True, default=None, max_length=300, null=True, verbose_name='Электронный адрес ')),
                ('contact_phone', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Контактный телефон ')),
                ('message', models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('judge', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='judge', to='court.judge', verbose_name='Судья Ф.И.О. ')),
                ('judge_help', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_help1', to='court.judge_help', verbose_name='Секретарь судьи ')),
            ],
            options={
                'verbose_name': 'Справочник судебных участков ',
                'verbose_name_plural': 'Справочник судебных участков',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='judge',
            name='judge_help',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_help', to='court.judge_help', verbose_name='Секретарь судьи '),
        ),
        migrations.CreateModel(
            name='InfoCourt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Номер Судебного дела')),
                ('uid_number', models.CharField(blank=True, default=None, max_length=26, null=True, verbose_name='УИД Судебного дела')),
                ('data_reg', models.DateField(blank=True, default=None, null=True, verbose_name='Дата регистрации дела')),
                ('message', models.TextField(blank=True, default=None, max_length=50000, null=True, verbose_name='Результат события Коментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('judge', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_judge', to='court.judge', verbose_name='Судья')),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='court.listcourt', verbose_name='Место  ')),
                ('status', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_status', to='court.status', verbose_name='Статус  дела')),
            ],
            options={
                'verbose_name': 'Информация дела',
                'verbose_name_plural': 'Информация дела',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_finish', models.DateField(blank=True, default=None, null=True, verbose_name='Срок исполнения С')),
                ('date_start', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Начало исполнения С')),
                ('date_stop', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Завершения исполнения С')),
                ('time_stop', models.DateField(blank=True, default=None, null=True, verbose_name='Время завершение операции ')),
                ('file_paste', models.FileField(blank=True, default=None, null=True, upload_to='upload/Courtdoc/', verbose_name='"Файл прикрепленный')),
                ('curt_hall', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Номер кабинета заседания')),
                ('message', models.CharField(blank=True, default=None, max_length=50000, null=True, verbose_name='Результат,коментарий события ')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('akt_end', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='akt_end', to='court.listend', verbose_name='Событие утверждения')),
                ('info_court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_courts', to='court.infocourt', verbose_name='Список юр.оперций ')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='court.procedure', verbose_name='Наименование события')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='court.worker', verbose_name='Отв-ный')),
            ],
            options={
                'verbose_name': 'Оперция судопроизводства',
                'verbose_name_plural': 'Оперции судопроизводства',
                'ordering': ['created'],
            },
        ),
    ]
