# Generated by Django 3.1.7 on 2021-06-29 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accident', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Событие утверждения')),
                ('message', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Список утверждения ',
                'verbose_name_plural': 'Списоки утверждения',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Имя операции ')),
                ('message', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Событие ',
                'verbose_name_plural': 'События',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Имя ')),
                ('surname', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Фамилия ')),
                ('midlename', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Отчество ')),
                ('phone', models.CharField(blank=True, default=None, max_length=13, null=True, verbose_name='Номер телефона')),
                ('post_mail', models.EmailField(blank=True, default=None, max_length=100, null=True, verbose_name='Адрес Эл.почты')),
                ('work_mail', models.EmailField(blank=True, default=None, max_length=100, null=True, verbose_name='Адрес Эл.почты рабочей')),
                ('link_social', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Адрес в соц.сети')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сотрудник ',
                'verbose_name_plural': 'Сотрудники ',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serves_hot_dogs', models.BooleanField(default=False, verbose_name='Исполнен')),
                ('data_finish', models.DateField(blank=True, default=None, null=True, verbose_name='Срок исполнения С')),
                ('date_start', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Начало исполнения С')),
                ('date_stop', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Завершения исполнения С')),
                ('time_stop', models.DateField(blank=True, default=None, null=True, verbose_name='Время завершение операции ')),
                ('file_paste', models.FileField(blank=True, default=None, null=True, upload_to='upload/Courtdoc/', verbose_name='"Файл прикрепленный')),
                ('curt_hall', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Номер кабинета заседания')),
                ('message', models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Результат события Коментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('akt_end', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='akt_end', to='court.listend', verbose_name='Событие утверждения')),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accident.accident', verbose_name='ДТП')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='court.procedure', verbose_name='Наименование события')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='court.worker', verbose_name='Отв-ный')),
            ],
            options={
                'verbose_name': 'Судебный процесс',
                'verbose_name_plural': 'Судебный процесс',
                'ordering': ['-created'],
            },
        ),
    ]
