# Generated by Django 3.1.7 on 2022-09-29 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcourt',
            name='judge',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge', to='court.judge', verbose_name='Судья Ф.И.О. '),
        ),
    ]
