# Generated by Django 3.1.7 on 2021-12-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0003_auto_20211207_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='info_court',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_court', to='court.infocourt', verbose_name='Список юр.оперций '),
        ),
    ]
