# Generated by Django 3.1.7 on 2021-12-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0005_remove_infocourt_accident'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocourt',
            name='judge',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_judge', to='court.judge', verbose_name='Судья'),
        ),
        migrations.AlterField(
            model_name='court',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Результат,коментарий события '),
        ),
    ]
