# Generated by Django 3.1.7 on 2021-12-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0006_auto_20211208_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judge',
            options={'ordering': ['-created'], 'verbose_name': 'Судья Ф.И.О ', 'verbose_name_plural': 'Судьи Ф.И.О'},
        ),
    ]
