# Generated by Django 3.1.7 on 2021-12-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0007_auto_20211209_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='message',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True, verbose_name='Результат,коментарий события '),
        ),
        migrations.AlterField(
            model_name='infocourt',
            name='message',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True, verbose_name='Результат события Коментарий'),
        ),
    ]
