# Generated by Django 3.1.7 on 2022-05-11 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('court', '0008_auto_20211209_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['created'], 'verbose_name': 'Оперция судопроизводства',
                     'verbose_name_plural': 'Оперции судопроизводства'},
        ),
        migrations.RemoveField(
            model_name='court',
            name='serves_hot_dogs',
        ),
        migrations.AlterField(
            model_name='court',
            name='akt_end',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='akt_end',
                                    to='court.listend', verbose_name='Событие утверждения'),
        ),
        migrations.AlterField(
            model_name='court',
            name='curt_hall',
            field=models.CharField(blank=True, default=None, max_length=24, verbose_name='Номер кабинета заседания'),
        ),
        migrations.AlterField(
            model_name='court',
            name='data_finish',
            field=models.DateField(blank=True, default=None, verbose_name='Срок исполнения С'),
        ),
        migrations.AlterField(
            model_name='court',
            name='date_start',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Начало исполнения С'),
        ),
        migrations.AlterField(
            model_name='court',
            name='date_stop',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Завершения исполнения С'),
        ),
        migrations.AlterField(
            model_name='court',
            name='file_paste',
            field=models.FileField(blank=True, default=None, upload_to='upload/Courtdoc/',
                                   verbose_name='"Файл прикрепленный'),
        ),
        migrations.AlterField(
            model_name='court',
            name='info_court',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_courts',
                                    to='court.infocourt', verbose_name='Список юр.оперций '),
        ),
        migrations.AlterField(
            model_name='court',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=50000,
                                   verbose_name='Результат,коментарий события '),
        ),
        migrations.AlterField(
            model_name='court',
            name='time_stop',
            field=models.DateField(blank=True, default=None, verbose_name='Время завершение операции '),
        ),
    ]
