# Generated by Django 3.1.7 on 2022-05-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('court', '0009_auto_20220511_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='info_court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_courts',
                                    to='court.infocourt', verbose_name='Список юр.оперций '),
        ),
    ]
