# Generated by Django 3.1.7 on 2022-04-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0009_auto_20220412_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['created'], 'verbose_name': 'Оперция судопроизводства', 'verbose_name_plural': 'Оперции судопроизводства'},
        ),
        migrations.AlterField(
            model_name='court',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True, verbose_name='Результат,коментарий события '),
        ),
    ]
