# Generated by Django 3.1.7 on 2022-05-15 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('court', '0011_auto_20220515_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='curt_hall',
            field=models.CharField(blank=True, default=None, max_length=24, null=True,
                                   verbose_name='Номер кабинета заседания'),
        ),
        migrations.AlterField(
            model_name='court',
            name='data_finish',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Срок исполнения С'),
        ),
        migrations.AlterField(
            model_name='court',
            name='date_start',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Начало исполнения С'),
        ),
        migrations.AlterField(
            model_name='court',
            name='date_stop',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Завершения исполнения С'),
        ),
        migrations.AlterField(
            model_name='court',
            name='file_paste',
            field=models.FileField(blank=True, default=None, null=True, upload_to='upload/Courtdoc/',
                                   verbose_name='"Файл прикрепленный'),
        ),
        migrations.AlterField(
            model_name='court',
            name='info_court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='info_courts', to='court.infocourt',
                                    verbose_name='Список юр.оперций '),
        ),
        migrations.AlterField(
            model_name='court',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True,
                                   verbose_name='Результат,коментарий события '),
        ),
        migrations.AlterField(
            model_name='court',
            name='time_stop',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Время завершение операции '),
        ),
    ]
