# Generated by Django 3.1.7 on 2022-05-05 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0012_auto_20220415_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='akt_end',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='akt_end', to='court.listend', verbose_name='Событие утверждения'),
        ),
        migrations.AlterField(
            model_name='court',
            name='info_court',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='info_courts', to='court.infocourt', verbose_name='Список юр.оперций '),
        ),
    ]
