# Generated by Django 3.1.7 on 2022-05-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0013_auto_20220505_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='serves_hot_dogs',
        ),
        migrations.AlterField(
            model_name='court',
            name='info_court',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_courts', to='court.infocourt', verbose_name='Список юр.оперций '),
        ),
    ]
