# Generated by Django 3.1.7 on 2021-06-29 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accident', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Статья')),
                ('comment', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Коментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статья ущерба  ',
                'verbose_name_plural': 'Статьи ущерба',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ExpertComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Наименование')),
                ('comment', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Описание')),
                ('mail_post', models.EmailField(blank=True, default=None, max_length=24, null=True, verbose_name='Адрес Эл.почты')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Экспертная орг. ',
                'verbose_name_plural': 'Экспертные орг.',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_doc', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Номер экспертизы')),
                ('data_in', models.DateField(blank=True, default=None, null=True, verbose_name='Дата отправления эксперту')),
                ('data_out', models.DateField(blank=True, default=None, null=True, verbose_name='Дата ответа эксперта')),
                ('price_nwear', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ВР без износа')),
                ('price_wwear', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ВР с износом')),
                ('price_mmarket', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Средняя по рынку')),
                ('price_uleftovers', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Годные остатки')),
                ('price_uts', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Сумма УТС')),
                ('price_summa', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Сумма ущерба')),
                ('comment', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Коментарий')),
                ('file_expert', models.FileField(blank=True, default=None, null=True, upload_to='upload/doc_expert/', verbose_name='"Файл Экспертизы')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('accident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accident.accident', verbose_name='Экспретиза')),
                ('contragent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contragent', to='client.company', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Экспертиза  ',
                'verbose_name_plural': 'Экспертные оценки',
                'ordering': ['-created'],
            },
        ),
    ]
