# Generated by Django 3.1.7 on 2021-10-12 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0003_auto_20211012_1054'),
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AlterField(
            model_name='expert',
            name='accident',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accident.accident', verbose_name='Экспретиза'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='comment',
            field=models.TextField(blank=True, default=None, max_length=100000, null=True, verbose_name='Коментарий'),
        ),
    ]
