# Generated by Django 3.1.7 on 2022-09-14 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Акт Осмотра'), (2, 'Экспертиза'), (3, 'Калькуляция')], default=None, null=True)),
                ('description', models.CharField(max_length=100, verbose_name='Описание ')),
                ('scan_doc', models.FileField(default=None, null=True, upload_to='media/expert/', verbose_name='Файл ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('files', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_expert', to='expert.expert', verbose_name='Прикрепленные файлы (Expert)')),
            ],
            options={
                'verbose_name': 'Файл Экспертизы',
                'verbose_name_plural': 'Файлы Экспертизы',
            },
        ),
    ]
