# Generated by Django 3.1.7 on 2021-12-01 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0012_auto_20211201_1445'),
        ('expert', '0002_auto_20211012_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='accident',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_accident', to='accident.accident', verbose_name='Экспретиза'),
        ),
    ]
