# Generated by Django 3.1.7 on 2022-09-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_expertfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='file_expert',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='file_invoce',
        ),
        migrations.AlterField(
            model_name='expertfiles',
            name='scan_doc',
            field=models.FileField(default=None, null=True, upload_to='media/doc_expert/', verbose_name='Файл '),
        ),
        migrations.AlterField(
            model_name='expertfiles',
            name='types',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Акт Осмотра'), (2, 'Экспертиза'), (3, 'Калькуляция'), (3, 'Скан чека')], default=None, null=True),
        ),
    ]
