# Generated by Django 3.1.7 on 2021-12-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_auto_20211201_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='summa_exp',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Стоимость экспертизы'),
        ),
    ]
