# Generated by Django 3.1.7 on 2022-09-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_auto_20220914_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertfiles',
            name='scan_doc',
            field=models.FileField(default=None, null=True, upload_to='media/doc_expert/', verbose_name='Файл'),
        ),
    ]
