# Generated by Django 3.1.7 on 2021-12-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0004_expert_summa_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='file_invoce',
            field=models.FileField(blank=True, default=None, null=True, upload_to='upload/doc_expert/invoice/', verbose_name='Файл скан чека'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='file_expert',
            field=models.FileField(blank=True, default=None, null=True, upload_to='upload/doc_expert/file/', verbose_name='Файл Экспертизы'),
        ),
    ]
