# Generated by Django 3.1.7 on 2021-12-02 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_partner_type'),
        ('expert', '0005_auto_20211201_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_client', to='client.client', verbose_name='Заказчик экспертизы'),
        ),
    ]
