# Generated by Django 3.1.7 on 2021-06-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=24, null=True, verbose_name='Имя ')),
                ('surname', models.CharField(blank=True, max_length=24, null=True, verbose_name='Фамилия ')),
                ('midlename', models.CharField(blank=True, max_length=24, null=True, verbose_name='Отчество ')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона')),
                ('phone2', models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона 1')),
                ('serial_pass', models.IntegerField(blank=True, help_text='Вводится 4 цифры без пробела', null=True, verbose_name='Серия паспорта')),
                ('number_pass', models.IntegerField(blank=True, help_text='Вводится 6 цифр без пробела', null=True, verbose_name='Номер паспорта')),
                ('enter_org', models.CharField(blank=True, help_text='УВД,ОВД,ЗАГС, МВД', max_length=50, null=True, verbose_name='Кем выдан')),
                ('data_create', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('adress_reg', models.CharField(blank=True, max_length=50, verbose_name='Место регистрации')),
                ('adress_home', models.CharField(blank=True, max_length=50, verbose_name='Место жительства')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('doc_pass', models.FileField(blank=True, default=None, upload_to='client/upload/pasport/', verbose_name='Фото паспорта')),
                ('serial_lic', models.CharField(blank=True, default=None, help_text='Вводится 4 цифры без пробела', max_length=24, null=True, verbose_name='Серия ВУ')),
                ('number_lic', models.CharField(blank=True, default=None, help_text='Вводится 6 цифр без пробела', max_length=100, null=True, verbose_name='Номер ВУ')),
                ('enter_lic', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Кем выдан ГИБДД')),
                ('create_lic', models.DateField(blank=True, default=None, null=True, verbose_name='Дата  выдачи')),
                ('adress_lic', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Место выдачи ВУ')),
                ('categiory', models.CharField(blank=True, default=None, help_text='B,C,D,E,BC,DE,A', max_length=50, null=True, verbose_name='Категории прав')),
                ('doc_lic', models.FileField(blank=True, default=None, null=True, upload_to='assets/img/products_images/', verbose_name='Фото ВУ')),
                ('post_mail', models.EmailField(blank=True, default=None, max_length=24, null=True, verbose_name='Адрес Эл.почты')),
                ('link_social', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Адрес в соц.сети')),
                ('attorney', models.DateField(blank=True, default=None, null=True, verbose_name='Дата  Окончание доверенности')),
                ('doc_attorney', models.FileField(blank=True, default=None, null=True, upload_to='upload/doc_attorney/', verbose_name='Файл Доверенности')),
                ('doc_requisites', models.FileField(blank=True, default=None, null=True, upload_to='upload/doc_requisites/', verbose_name='Файл Реквизитов банк')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клиент  ',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Название компании')),
                ('full_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Полное название компании')),
                ('nalog_number', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='ИНН ')),
                ('nalog_main', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='ОГРН')),
                ('nalog_registr', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='КПП')),
                ('company_adress', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Адрес юридический')),
                ('number_phone', models.CharField(blank=True, default=None, max_length=13, null=True, verbose_name='Контактный номер телефона')),
                ('mail_adress', models.EmailField(blank=True, default=None, max_length=50, null=True, verbose_name='Адрес эл.почты')),
                ('director_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Директор Ф.И.О')),
                ('doc_image', models.FileField(blank=True, default=None, help_text='Прикрепленный файл', null=True, upload_to='upload/company/contragent/', verbose_name='Файл карточка компании')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты ',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Имя контакта')),
                ('number', models.CharField(blank=True, default=None, max_length=14, null=True, verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Телефон клиента',
                'verbose_name_plural': 'Телефоны клиентов',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статус клиента',
                'verbose_name_plural': 'Статусы клиентов',
            },
        ),
        migrations.CreateModel(
            name='Сontract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_pdf', models.FileField(blank=True, default=None, null=True, upload_to='upload/ContactDoc/', verbose_name='Договор')),
                ('summa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма Контракта')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Договор с клиентом  ',
                'verbose_name_plural': 'Договора клиентов ',
                'ordering': ['-created'],
            },
        ),
    ]
