# Generated by Django 3.1.7 on 2021-08-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='enter_org',
            field=models.CharField(blank=True, help_text='УВД,ОВД,ЗАГС, МВД', max_length=100, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона 1'),
        ),
    ]
