# Generated by Django 3.1.7 on 2021-08-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210809_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='point_birth',
            field=models.CharField(blank=True, max_length=50, verbose_name='Место рождение'),
        ),
    ]
