# Generated by Django 3.1.7 on 2021-08-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_point_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='site_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка на сайт'),
        ),
        migrations.AlterField(
            model_name='company',
            name='full_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Полное наименование компании'),
        ),
    ]
