# Generated by Django 3.1.7 on 2021-08-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210819_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_adress',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Юр.адрес банка'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_bik',
            field=models.IntegerField(blank=True, default=None, max_length=9, null=True, verbose_name='БИК банка'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_edit_invoice',
            field=models.IntegerField(blank=True, default=None, max_length=20, null=True, verbose_name='Кор/счет'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_invoice',
            field=models.IntegerField(blank=True, default=None, max_length=20, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Наименование банка'),
        ),
        migrations.AlterField(
            model_name='client',
            name='serial_pass',
            field=models.CharField(blank=True, help_text='Вводится 4 цифры без пробела', max_length=5, null=True, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='company',
            name='site_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Сайт компании'),
        ),
    ]
