# Generated by Django 3.1.7 on 2021-08-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20210819_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bank_edit_invoice',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Кор/счет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bank_invoice',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Расчетный счет'),
        ),
    ]
