# Generated by Django 3.1.7 on 2021-08-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20210819_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bank_bik',
            field=models.CharField(blank=True, default=None, max_length=9, null=True, verbose_name='БИК банка'),
        ),
    ]
