# Generated by Django 3.1.7 on 2021-08-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20210819_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='draft',
        ),
        migrations.AddField(
            model_name='company',
            name='Comment',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Комментарий'),
        ),
    ]
