# Generated by Django 3.1.7 on 2021-08-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20210819_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Comment',
            field=models.TextField(blank=True, default=None, max_length=400, null=True, verbose_name='Комментарий'),
        ),
    ]
