# Generated by Django 3.1.7 on 2021-11-08 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0004_auto_20211108_1943'),
        ('client', '0010_auto_20211012_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='accident',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accident', to='accident.accident', verbose_name='ДТП'),
        ),
    ]
