# Generated by Django 3.1.7 on 2021-11-14 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0015_auto_20211112_1225'),
        ('accident', '0009_auto_20211114_1514'),
        ('client', '0011_client_accident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('accident', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ДТП', to='accident.accident', verbose_name='ДТП ')),
                ('car', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='auto.car', verbose_name='ТС  физ. лица ')),
            ],
            options={
                'verbose_name': 'Участник ДТП',
                'verbose_name_plural': 'Участники ДТП',
            },
        ),
        migrations.RenameField(
            model_name='client',
            old_name='categiory',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='client',
            name='accident',
        ),
        migrations.RemoveField(
            model_name='client',
            name='side',
        ),
        migrations.AddField(
            model_name='status',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Наименование'),
        ),
        migrations.DeleteModel(
            name='Side',
        ),
        migrations.AddField(
            model_name='partner',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.client', verbose_name='Физ. лицо  '),
        ),
        migrations.AddField(
            model_name='partner',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='client.status', verbose_name='Статус в ДТП  '),
        ),
    ]
