# Generated by Django 3.1.7 on 2021-11-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0010_auto_20211114_1606'),
        ('auto', '0015_auto_20211112_1225'),
        ('client', '0013_auto_20211114_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='accident',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_accident', to='accident.accident', verbose_name='ДТП '),
        ),
        migrations.AlterField(
            model_name='partner',
            name='car',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_car', to='auto.car', verbose_name='ТС  физ. лица '),
        ),
        migrations.AlterField(
            model_name='partner',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_client', to='client.client', verbose_name='Физ. лицо  '),
        ),
    ]
