# Generated by Django 3.1.7 on 2021-11-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20211114_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='type',
            field=models.BooleanField(default=False, verbose_name='Клиент '),
        ),
    ]
