# Generated by Django 3.1.7 on 2022-03-16 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0016_partner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='link_social',
            field=models.URLField(blank=True, default=None, max_length=24, null=True, verbose_name='Адрес в соц.сети'),
        ),
        migrations.AlterField(
            model_name='client',
            name='post_mail',
            field=models.EmailField(blank=True, max_length=24, null=True, verbose_name='Адрес Эл.почты'),
        ),
        migrations.AlterField(
            model_name='company',
            name='site_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Сайт компании'),
        ),
        migrations.CreateModel(
            name='FilePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.PositiveSmallIntegerField(
                    choices=[(1, 'Паспорт'), (2, 'Вод.Удост'), (3, 'Реквизиты'), (4, 'Доверенность')])),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('scan_doc',
                 models.FileField(blank=True, default=None, null=True, upload_to='media/person/', verbose_name='Файл')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('files_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='files_person', to='client.client',
                                                   verbose_name='Прикрепленные файлы (Client)')),
            ],
        ),
        migrations.CreateModel(
            name='FileCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.PositiveSmallIntegerField(
                    choices=[(1, 'Выписка ОГРН'), (2, 'Реквезиты'), (3, 'Доверенность')])),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('scan_doc', models.FileField(blank=True, default=None, null=True, upload_to='media/company/',
                                              verbose_name='Файл')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('files_comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='files_company', to='client.company',
                                                 verbose_name='Прикрепленные файлы (Company)')),
            ],
        ),
    ]
