# Generated by Django 3.1.7 on 2022-03-16 06:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0019_auto_20220316_1303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilePerson',
            new_name='FilePerson1',
        ),
        migrations.RenameField(
            model_name='fileperson1',
            old_name='files_persons',
            new_name='files_person',
        ),
    ]
