# Generated by Django 3.1.7 on 2022-03-16 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0020_auto_20220316_1308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilePerson1',
            new_name='FilePerson',
        ),
    ]
