# Generated by Django 3.1.7 on 2022-03-16 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0021_auto_20220316_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filecompany',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='fileperson',
            name='is_active',
        ),
    ]
