# Generated by Django 3.1.7 on 2022-03-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0022_auto_20220316_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filecompany',
            options={'verbose_name': 'Файл Юр.лиц', 'verbose_name_plural': 'Файлы Юр.лиц'},
        ),
        migrations.AlterModelOptions(
            name='fileperson',
            options={'verbose_name': 'Файл Физ.лиц', 'verbose_name_plural': 'Файлы Физ.лиц'},
        ),
        migrations.AlterField(
            model_name='filecompany',
            name='types',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Выписка ОГРН'), (2, 'Реквезиты'), (3, 'Доверенность')],
                                                   verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='fileperson',
            name='types',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Паспорт'), (2, 'Вод.Удост'), (3, 'Реквизиты'), (4, 'Доверенность')], verbose_name='Тип'),
        ),
    ]
