# Generated by Django 3.1.7 on 2022-03-21 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0023_auto_20220316_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecompany',
            name='author',
            field=models.OneToOneField(blank=True, db_column='user', null=True,
                                       on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileperson',
            name='author',
            field=models.OneToOneField(blank=True, db_column='user', null=True,
                                       on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filecompany',
            name='types',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(1, 'Выписка ОГРН'), (2, 'Реквезиты'), (3, 'Доверенность')],
                                                   default=None, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='fileperson',
            name='types',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(1, 'Паспорт'), (2, 'Вод.Удост'), (3, 'Реквизиты'),
                                                            (4, 'Доверенность')], default=None, null=True,
                                                   verbose_name='Тип'),
        ),
    ]
