# Generated by Django 3.1.7 on 2022-03-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0024_auto_20220321_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='doc_image',
        ),
        migrations.AlterField(
            model_name='filecompany',
            name='types',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(1, 'Выписка ОГРН'), (2, 'Реквезиты'), (3, 'Доверенность'),
                                                            (4, 'Карточка контрагента')], default=None, null=True,
                                                   verbose_name='Тип'),
        ),
    ]
