# Generated by Django 3.1.7 on 2022-05-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0025_auto_20220322_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecompany',
            name='scan_doc',
            field=models.FileField(default=None, null=True, upload_to='media/company/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='fileperson',
            name='scan_doc',
            field=models.FileField(default=None, null=True, upload_to='media/person/', verbose_name='Файл'),
        ),
    ]
