# Generated by Django 3.1.7 on 2021-06-29 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Тип документа')),
                ('full_name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Полное наименование')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Док основание  ДТП',
                'verbose_name_plural': 'Док основание  ДТП',
            },
        ),
        migrations.CreateModel(
            name='AccidentPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Тип документа')),
                ('full_name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Полное наименование')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Док опеределение ДТП',
                'verbose_name_plural': 'Док определение ДТП',
            },
        ),
        migrations.CreateModel(
            name='judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Судья Ф.И.О. ')),
                ('adress_mail', models.EmailField(blank=True, default=None, max_length=300, null=True, verbose_name='Электронный адрес ')),
                ('contact_phone', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Контактный телефон ')),
                ('message', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Судья фамилия ',
                'verbose_name_plural': 'Судьи фамилии',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='judge_help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Помошник судьи  ФИО')),
                ('message', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Помошник судьи ',
                'verbose_name_plural': 'Помошники судей',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ListCourt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Наименование суда ')),
                ('adress', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Адрес Суда ')),
                ('adress_post', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Почтовый адрес ')),
                ('adress_mail', models.EmailField(blank=True, default=None, max_length=300, null=True, verbose_name='Электронный адрес ')),
                ('contact_phone', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Контактный телефон ')),
                ('message', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('judge', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='judge', to='accident.judge', verbose_name='Судья Ф.И.О. ')),
                ('judge_help', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_help1', to='accident.judge_help', verbose_name='Секретарь судьи ')),
            ],
            options={
                'verbose_name': 'Справочник судебных участков ',
                'verbose_name_plural': 'Справочник судебных участков',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='judge',
            name='judge_help',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_help', to='accident.judge_help', verbose_name='Секретарь судьи '),
        ),
        migrations.CreateModel(
            name='InfoCourt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Номер Судебного дела')),
                ('uid_number', models.CharField(blank=True, default=None, max_length=26, null=True, verbose_name='УИД Судебного дела')),
                ('data_reg', models.DateField(blank=True, default=None, null=True, verbose_name='Дата регистрации дела')),
                ('message', models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Результат события Коментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='accident.listcourt', verbose_name='Место  ')),
            ],
            options={
                'verbose_name': 'Информация дела',
                'verbose_name_plural': 'Информация дела',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, default=None, null=True, verbose_name='Дата ДТП ')),
                ('time', models.TimeField(blank=True, default=None, null=True, verbose_name='Время ДТП ')),
                ('number', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Номер протокола')),
                ('doc_isk', models.BooleanField(default=None, help_text='Исковое заявление', verbose_name='Исковое заявление')),
                ('doc_pos', models.BooleanField(default=None, help_text='Пошлина', verbose_name='Пошлина')),
                ('doc_spr', models.BooleanField(default=None, help_text='Экспертиза', verbose_name='Экспертиза')),
                ('doc_dtp', models.BooleanField(default=None, help_text='Протокол ДТП', verbose_name='Протокол ДТП')),
                ('doc', models.FileField(blank=True, default=None, null=True, upload_to='upload/protokol_doc/', verbose_name='Файл Основание')),
                ('doc_1', models.FileField(blank=True, default=None, null=True, upload_to='upload/protokol_doc/', verbose_name='Файл Дополнение')),
                ('case_number', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='N дела')),
                ('uid_number', models.CharField(blank=True, default=None, max_length=26, null=True, verbose_name='UID дела')),
                ('data_reg', models.DateField(blank=True, default=None, null=True, verbose_name='Дата регистрации дела')),
                ('location_accident', models.CharField(blank=True, default=None, max_length=400, verbose_name='Место ДТП')),
                ('data_insurance', models.DateField(blank=True, default=None, null=True, verbose_name='Дата обращения в Страховую')),
                ('message', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('car_culprit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_culprit', to='auto.car', verbose_name='Автомобиль ответчика ')),
                ('car_plaintiff', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='car_plaintiff', to='auto.car', verbose_name='Автомобиль истца ')),
                ('culprit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='culprit', to='client.client', verbose_name='Ответчик ')),
                ('dtp_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccidentDoc', to='accident.accidentdoc', verbose_name='Документ Основание ')),
                ('dtp_pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccidentPos', to='accident.accidentpos', verbose_name='Документ Постановление ')),
                ('location_court', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location1', to='accident.listcourt', verbose_name='Судебный участок  ')),
                ('plaintiff', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plaintiff', to='client.client', verbose_name='Истец ')),
            ],
            options={
                'verbose_name': 'ДТП  ',
                'verbose_name_plural': 'ДТП',
                'ordering': ['-created'],
            },
        ),
    ]
