# Generated by Django 3.2.4 on 2021-06-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='dtp_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccidentDoc1', to='accident.accidentdoc', verbose_name='Документ Основание '),
        ),
    ]
