# Generated by Django 3.1.7 on 2021-10-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0002_alter_accident_dtp_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcourt',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Комментарий'),
        ),
    ]
