# Generated by Django 3.1.7 on 2021-11-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0003_auto_20211012_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='car_culprit',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='car_plaintiff',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='culprit',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='plaintiff',
        ),
    ]
