# Generated by Django 3.1.7 on 2021-11-10 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0004_auto_20211108_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статус  ДТП',
                'verbose_name_plural': 'Статусы ДТП',
            },
        ),
        migrations.RenameField(
            model_name='accident',
            old_name='doc',
            new_name='file_doc',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='doc_1',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='doc_dtp',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='doc_isk',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='doc_pos',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='doc_spr',
        ),
        migrations.AddField(
            model_name='accident',
            name='file_pos',
            field=models.FileField(blank=True, default=None, null=True, upload_to='upload/protokol_pos/', verbose_name='Файл Постановление'),
        ),
        migrations.AddField(
            model_name='accident',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='dtp_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_doc', to='accident.accidentdoc', verbose_name='Документ Основание '),
        ),
        migrations.AddField(
            model_name='accident',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='accident.status', verbose_name='Статус ДТП'),
        ),
    ]
