# Generated by Django 3.1.7 on 2021-11-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0005_auto_20211110_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
