# Generated by Django 3.1.7 on 2021-11-10 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0006_auto_20211110_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=200),
        ),
    ]
