# Generated by Django 3.1.7 on 2021-11-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0007_auto_20211110_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Наименование'),
        ),
    ]
