# Generated by Django 3.1.7 on 2021-11-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0008_auto_20211112_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='judge_help',
        ),
        migrations.RemoveField(
            model_name='listcourt',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='listcourt',
            name='judge_help',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='data_reg',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='location_court',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='uid_number',
        ),
        migrations.DeleteModel(
            name='InfoCourt',
        ),
        migrations.DeleteModel(
            name='judge',
        ),
        migrations.DeleteModel(
            name='judge_help',
        ),
        migrations.DeleteModel(
            name='ListCourt',
        ),
    ]
