# Generated by Django 3.1.7 on 2021-11-24 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0010_auto_20211114_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус  дела о ДТП', 'verbose_name_plural': 'Статусы дела о ДТП'},
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_acc', to='accident.status', verbose_name='Статус  дела о ДТП'),
        ),
    ]
