# Generated by Django 3.1.7 on 2021-12-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0011_auto_20211124_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=100000, null=True, verbose_name='Комментарий'),
        ),
    ]
