# Generated by Django 3.1.7 on 2021-08-31 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0009_auto_20210819_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Название документа ')),
                ('location', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Местоположение ')),
                ('author', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Автор документа')),
                ('customer', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Заказчик ')),
                ('comment', models.CharField(blank=True, default=None, max_length=3000, null=True, verbose_name='Комментарий ')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('executor', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='client.company', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Body_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Название объекта  док')),
                ('text', models.TextField(blank=True, default=None, max_length=10000, null=True, verbose_name='Поле объекта док ')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='document.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'поле документа',
                'verbose_name_plural': 'поля документа',
            },
        ),
    ]
