# Generated by Django 3.1.7 on 2021-10-12 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20211012_1054'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Таблица ')),
                ('comment', models.CharField(blank=True, default=None, max_length=3000, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Модель БД ',
                'verbose_name_plural': 'Модели БД',
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='executor',
            field=models.ForeignKey(blank=True, default=None, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='client.company', verbose_name='Исполнитель'),
        ),
        migrations.CreateModel(
            name='Document_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Наименование ')),
                ('tags', models.TextField(blank=True, default=None, max_length=50, null=True, verbose_name='Тэг')),
                ('model', models.TextField(blank=True, default=None, max_length=50, null=True, verbose_name='Поле модели')),
                ('comment', models.CharField(blank=True, default=None, max_length=3000, null=True, verbose_name='Комментарий ')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='document.table', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Список тэгов в шаблоне',
                'verbose_name_plural': 'Список тэгов в шаблоне',
            },
        ),
    ]
