# Generated by Django 3.1.7 on 2022-06-26 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Марка ТС ')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Марка ТС',
                'verbose_name_plural': 'Марки ТС',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Гос.номер ')),
                ('color', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Цвет')),
                ('date_made', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('sts_s', models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Серия СТС')),
                ('sts_n', models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='Номер СТС')),
                ('sts_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата выдачи СТС')),
                ('pts_s', models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Серия ПТС')),
                ('pts_n', models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='Номер ПТС')),
                ('pts_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата выдачи ПТС')),
                ('vin', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='VIN номер')),
                ('driver', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Сделать ссылку на клиента ')),
                ('Comment', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('marka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marka', to='auto.brend', verbose_name='Марка ')),
            ],
            options={
                'verbose_name': 'Транспортное средство  ',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Модель ТС ')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand_auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.brend', verbose_name='Марка Авто')),
            ],
            options={
                'db_table': 'automarket_target_model',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ОСАГО'), (2, 'Каско'), (3, 'Доп.соглашение')], null=True)),
                ('i_serial', models.CharField(max_length=10, verbose_name='Серия ')),
                ('i_number', models.CharField(max_length=15, verbose_name='Номер')),
                ('start_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата выдачи')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата окончания')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_auto', to='auto.car', verbose_name=' Полисы страхования ТС')),
            ],
            options={
                'verbose_name': 'Страховой документ ТС',
                'verbose_name_plural': 'Страховые  документы ТС',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='auto.model', verbose_name='Модель '),
        ),
        migrations.CreateModel(
            name='AutoFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ПТС'), (2, 'СТС'), (3, 'Договор КП'), (4, 'ОСАГО'), (5, 'КАСКО')], default=None, null=True)),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('scan_doc', models.FileField(default=None, null=True, upload_to='media/auto/', verbose_name='Файл')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('files', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_auto', to='auto.car', verbose_name='Прикрепленные файлы (Car)')),
            ],
            options={
                'verbose_name': 'Файл ТС',
                'verbose_name_plural': 'Файлы ТС',
            },
        ),
    ]
