# Generated by Django 3.1.7 on 2021-08-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pst_s',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Серия ПТС'),
        ),
        migrations.AddField(
            model_name='car',
            name='sts_s',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Серия СТС'),
        ),
    ]
