# Generated by Django 3.1.7 on 2021-08-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_auto_20210812_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='pst_n',
            new_name='pts_n',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='pst_s',
            new_name='pts_s',
        ),
    ]
