# Generated by Django 3.1.7 on 2021-08-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_auto_20210812_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='pts_data',
            new_name='pts_date',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='sts_data',
            new_name='sts_date',
        ),
    ]
