# Generated by Django 3.1.7 on 2021-10-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_auto_20210819_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doc_pass',
            field=models.FileField(blank=True, default=None, null=True, upload_to='upload/client/pasport/', verbose_name='Фото ПТС'),
        ),
    ]
