# Generated by Django 3.1.7 on 2021-10-13 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_auto_20211012_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[(1, 'photo'), (2, 'car')], max_length=5)),
                ('description', models.CharField(max_length=100)),
                ('doc_pass', models.FileField(blank=True, default=None, null=True, upload_to='media/auto/', verbose_name='Фото ПТС')),
                ('files', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Файлы', to='auto.car', verbose_name='Прикрепленные фалы')),
            ],
        ),
    ]
