# Generated by Django 3.1.7 on 2021-10-13 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='doc_pass',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/auto/', verbose_name='Скан  ПТС'),
        ),
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_all', to='auto.car', verbose_name='Прикрепленные файлы'),
        ),
        migrations.AlterField(
            model_name='file',
            name='types',
            field=models.PositiveSmallIntegerField(choices=[(1, 'photo'), (2, 'car')], max_length=5),
        ),
    ]
