# Generated by Django 3.1.7 on 2021-10-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_auto_20211013_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='types',
            field=models.PositiveSmallIntegerField(choices=[(1, 'photo'), (2, 'car')]),
        ),
    ]
