# Generated by Django 3.1.7 on 2021-10-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0010_auto_20211013_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
    ]
