# Generated by Django 3.1.7 on 2021-11-03 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0012_auto_20211013_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files1', to='auto.car', verbose_name='Прикрепленные файлы (Car)'),
        ),
        migrations.AlterField(
            model_name='file',
            name='types',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ПТС'), (2, 'СТС'), (3, 'Договор КП'), (4, '')]),
        ),
    ]
