# Generated by Django 3.1.7 on 2021-11-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_client_accident'),
        ('auto', '0013_auto_20211103_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='human',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='human', to='client.client', verbose_name=' Клиент'),
        ),
    ]
