# Generated by Django 3.1.7 on 2022-05-31 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auto', '0017_auto_20220511_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofiles',
            name='files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files1', to='auto.car',
                                    verbose_name='Прикрепленные файлы (Car)'),
        ),
        migrations.AlterField(
            model_name='autofiles',
            name='scan_doc',
            field=models.FileField(default=None, null=True, upload_to='media/auto/', verbose_name='Файл'),
        ),
    ]
