# Generated by Django 3.1.7 on 2022-05-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0017_auto_20220504_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofiles',
            name='scan_doc',
            field=models.FileField(default=None, null=True, upload_to='media/auto/', verbose_name='Файл'),
        ),
    ]
