# Generated by Django 3.1.7 on 2022-05-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0018_auto_20220530_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofiles',
            name='scan_doc',
            field=models.FileField(null=True, upload_to='media/auto/', verbose_name='Файл'),
        ),
    ]
