# Generated by Django 3.1.7 on 2022-05-31 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auto', '0018_auto_20220531_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofiles',
            name='files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_auto',
                                    to='auto.car', verbose_name='Прикрепленные файлы (Car)'),
        ),
    ]
