# Generated by Django 3.1.7 on 2022-05-31 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auto', '0019_auto_20220531_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofiles',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='files_auto', to='auto.car', verbose_name='Прикрепленные файлы (Car)'),
        ),
        migrations.AlterField(
            model_name='autofiles',
            name='types',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(1, 'ПТС'), (2, 'СТС'), (3, 'Договор КП'), (4, 'ОСАГО'),
                                                            (5, 'КАСКО')], default=None, null=True),
        ),
    ]
