# Generated by Django 3.1.7 on 2022-06-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0020_auto_20220530_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofiles',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_auto', to='auto.car', verbose_name='Прикрепленные файлы (Car)'),
        ),
        migrations.AlterField(
            model_name='autofiles',
            name='scan_doc',
            field=models.FileField(default=None, null=True, upload_to='media/auto/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='autofiles',
            name='types',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ПТС'), (2, 'СТС'), (3, 'Договор КП'), (4, 'ОСАГО'), (5, 'КАСКО')], default=None, null=True),
        ),
    ]
